- .env.dist
- .github/workflows/image.yaml
- LICENSE
- README.md
- Taskfile.yml
- go.mod
- proxy.go
- runtime/common/common1.17.1/Dockerfile
- runtime/golang/v1.20/Dockerfile
- runtime/golang/v1.21/Dockerfile
- runtime/golang/v1.22/Dockerfile
- runtime/java/v11/Dockerfile
- runtime/java/v17/Dockerfile
- runtime/java/v21/Dockerfile
- runtime/java/v8/Dockerfile
- runtime/nodejs/v18/Dockerfile
- runtime/nodejs/v20/Dockerfile
- runtime/nodejs/v21/Dockerfile
- runtime/php/v8.0/Dockerfile
- runtime/php/v8.1/Dockerfile
- runtime/php/v8.2/Dockerfile
- runtime/php/v8.3/Dockerfile
- runtime/python/v3.10/Dockerfile
- runtime/python/v3.11/Dockerfile
- runtime/python/v3.11ca/Dockerfile
- runtime/python/v3.12/Dockerfile
> go module renaming

- .github/workflows/image.yaml
- .gitignore
- .licenserc.yaml
- go.mod
- proxy.go
- runtime/common/common1.17.1/Dockerfile
> Prepare for common TAG

- .github/workflows/image.yaml
- .licenserc.yaml
- DISCLAIMER
- NOTICE
- NOTICE.txt
- Taskfile.yml
This PR adds an initial implementation of GitHub actions to perform build action on push or pull_request flows
> tag and PR based builds

- .github/workflows/image.yaml
- .licenserc.yaml
- Taskfile.yml
- customkitd.toml
Initial version of GitHub actions using a custom docker cloud builder
> Initial version of GitHub actions using a custom docker cloud builder

- .github/workflows/common..yaml
- Taskfile.yml
chore: github action to deploy common runtime
> chore: github action to deploy common runtime

- .github/workflows/common..yaml
- Taskfile.yml
GitHub action to build common runtime based on TAG
> GitHub action to build common runtime based on TAG

- .github/workflows/common.yaml
- .github/workflows/image.yaml
> Testing common build

- .github/workflows/common.yaml
- Taskfile.yml
using task based build for common runtime
> Fix: using task based build for common runtime

- .github/workflows/common.yaml
- .github/workflows/image.yaml
- .gitignore
- .licenserc.yaml
- README.md
- Taskfile.yml
- runtime/java/v11/Dockerfile
- runtime/java/v17/Dockerfile
- runtime/java/v21/Dockerfile
- runtime/java/v8/Dockerfile
- runtimes.json.tpl
chore: added task render-runtimes to generate a runtimes.json tarting from current tag
> chore: added a task to generate runtimes.json according to current tag

- openwhisk/version.go
- runtime/common/common1.21.0/Dockerfile
chore: preparing common 1.21.0
> chore: preparing common 1.21.0

- runtime/common/common1.21.0/Dockerfile
> chore: prepare release 1.21.0

- .github/workflows/common.yaml
- openwhisk/forward_proxy.go
- openwhisk/forward_proxy_test.go
- openwhisk/version.go
- runtime/common/common1.18.0/Dockerfile
feature: preparing common1.18.0
> feature: preparing common1.18.0

- .github/workflows/common.yaml
> chore: fix in common builder action

- README.md
- Taskfile.yml
- openwhisk/version.go
- runtime/common/common1.18.1/Dockerfile
- runtime/experimental/python/v3.11cuda/requirements.txt
- runtime/go/v1.22proxy/Dockerfile
This PR prepares the release common1..18.1 which is contribution a common runtime with capabilities to perform remote action cleanup when in proxy client mode.
> Common1.18.1 release preparation

- .github/workflows/image.yaml
update to image builder github action to use OnePassword configured common
> chore: update to image builder github action to use OnePassword based config

- openwhisk/forward_proxy.go
- openwhisk/runHandler.go
This PR adds some debug logs to better separate client and remote logs
> Mode debug logs

- .gitignore
- Taskfile.yml
- packages/python/phi.py
- runtime/common/common1.18.3/Dockerfile
- runtime/experimental/python/v3.11cuda/debug.sh
> Prepares for common1.18.3

- .github/workflows/experimental.yaml
- Taskfile.yml
adds github action for experimental runtimes
> chore: adds github action for experimental runtimes

- .github/workflows/experimental.yaml
> adds github action for experimental runtimes

- .github/workflows/experimental.yaml
- Taskfile.yml
fix experimental GitHub action
> fix experimental GitHub action

- .github/workflows/experimental.yaml
> chore: using full docker hub path

- runtime/java/v11/Dockerfile
- runtime/java/v11/bin/compile
- runtime/java/v17/Dockerfile
- runtime/java/v17/bin/compile
- runtime/java/v21/Dockerfile
- runtime/java/v21/bin/compile
- runtime/java/v8/Dockerfile
- runtime/java/v8/bin/compile
Gson update from 2.9.0 to 2.11.0
> Update from gson 2.9.0 to 2.11.0

- runtime/java/v17/lib/src/Launcher.java
- runtime/java/v21/lib/src/Launcher.java
Ciao
Small changed for use of Map interface instead of HashMap, 
better diamond declatation 
and use of standard charset
I have modified java v17 and v21 runtime
ciao
matteo
> Improve code quality

- runtime/python/v3.10/requirements.txt
- runtime/python/v3.11/requirements.txt
- runtime/python/v3.11ca/requirements.txt
- runtime/python/v3.12/requirements.txt
updates libraries in python runtimes
> updates libraries in python runtimes

- .gitignore
- packages/python/mistral.py
- runtime/experimental/python/v3.11cuda/Dockerfile
- runtime/experimental/python/v3.11cuda/requirements.txt
pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
> update experimental runtime to pytorch/pytorch:2.5.1-cuda12.4

- runtime/python/v3.10/requirements.txt
- runtime/python/v3.11/requirements.txt
- runtime/python/v3.11ca/requirements.txt
- runtime/python/v3.12/requirements.txt
Added bcrypt==4.2.1 to requirements. To be used in system login action
> chore: added bcrypt
